### ISSUE TITLE
Repo ka name change karo capital d likho small hatao

### ISSUE THREAD

**Issue by Tanmay-Tiwaricyber** [Sameer370Draken/sameer370draken#1]
😂😂😂😂😂😂😂😂😂😂🤐

**Comment by Sameer370Draken** [comment]
Kon seee repo me 
Aur ek bat aur mera banner dekha 😁😁

@Tanmay-Tiwaricyber

**Comment by Tanmay-Tiwaricyber** [comment]
(https://github.com/Sameer370Draken)
/
(https://github.com/Sameer370Draken/sameer370draken)

Es wali repo me

**Comment by Tanmay-Tiwaricyber** [comment]
> Kon seee repo me Aur ek bat aur mera banner dekha gringrin
> 
> @Tanmay-Tiwaricyber

Saale mera banner copy kar liya pura😂

😂😂😂😂😂
😈(nhi) 

@Tanmay-Tiwaricyber

**Comment by Tanmay-Tiwaricyber** [comment]
🏃‍♂️d

**Comment by Tanmay-Tiwaricyber** [comment]
👧🎯

**Comment by Sameer370Draken** [comment]
How do I put an image on a whole body in html 
@Tanmay-Tiwaricyber

**Comment by Sameer370Draken** [comment]
Jaldi reply dooo bhai 😅😅😈😈😈😈 
@Tanmay-Tiwaricyber
